### ISSUE TITLE
Stat bars displaying over other UIs

### ISSUE THREAD

**Issue by Intecpsp** [Varietyz/literegenmeter#2]
Can the priority of the stat bars be lowered or lowerable/configurable?

![Screenshot 2024-10-14 at 2 59 55 PM](https://github.com/user-attachments/assets/33058454-1929-429f-9eea-bbce6ac25b0f)

**Comment by Varietyz** [comment]
> Can the priority of the stat bars be lowered or lowerable/configurable?
> 
> ![Screenshot 2024-10-14 at 2 59 55 PM](https://private-user-images.githubusercontent.com/1164012/376358128-33058454-1929-429f-9eea-bbce6ac25b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzMzNjUsIm5iZiI6MTcyODkzMzA2NSwicGF0aCI6Ii8xMTY0MDEyLzM3NjM1ODEyOC0zMzA1ODQ1NC0xOTI5LTQyOWYtOWVlYS1iYmNlNmFjMjViMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTkxMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTcyOWY1ZmRhNWJhOWUwM2UyMDRiMzlhNGFhMzcyNzc5Mjk1YTI1MDU5YjA4MGRkNjA2ODQyZmI2ZTU1OGQ0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hvNoRSWKxbuo-3pIyn5bhvaahyIavbBY5d1pVZtvtOg)

You must reach out to the creator of the plugin you are using there, he has to set his widget to display above all.

The priority on statbars is defined correctly.
