### ISSUE TITLE
HP Orb icon gets offset when Poisoned [Vanilla theme]

### ISSUE THREAD

**Issue by its-cue** [Varietyz/literegenmeter#3]
Noticed when you get poisoned it replaces the Icon when using a resource pack, but also offsets the X coordinate even when using Vanilla theme

1st orb, Config option to change poison is disabled 
2nd orb, When poison is cleared the offset still remains 
3rd orb, Before being poisoned (while using a custom icon)

![image](https://github.com/user-attachments/assets/b3e07f1f-ea4d-41a6-802a-4e8f89b76b32)

**Comment by Varietyz** [comment]
> Noticed when you get poisoned it replaces the Icon when using a resource pack, but also offsets the X coordinate even when using Vanilla theme
> 
> 1st orb, Config option to change poison is disabled 2nd orb, When poison is cleared the offset still remains 3rd orb, Before being poisoned (while using a custom icon)
> 
> ![image](https://private-user-images.githubusercontent.com/126547120/378110548-b3e07f1f-ea4d-41a6-802a-4e8f89b76b32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MTM0MjgsIm5iZiI6MTcyOTQxMzEyOCwicGF0aCI6Ii8xMjY1NDcxMjAvMzc4MTEwNTQ4LWIzZTA3ZjFmLWVhNGQtNDFhNi04MDJhLTRlOGY4OWI3NmIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQwODMyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTE1ZGFkZjVkNzM1MzJiZDU1ZWZkMzhlYWU4ZDE5YTVmODY0NDNhOWY2NzA0NWE2NjE3OGVhZDZhODJkMGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2se1RtljsdXjaub782IN0mUKvyxP3q_EJ31DVm_Ah8k)

After a poison is cleared, the original sprite is placed. i have been looking for a way to replace the original theme pack sprite, but i have not yet found a solution for it.

to visualize the poison orb, it removes the original sprite and places the custom poison orbs. 
When poison effect ends, the custom poison orb gets removed and the original osrs health sprite is being placed in its place again.

Problem there is, that the resource pack does not re-override the sprite with custom one :(

The issue that causes it is known, the solution however is still somewhat a gray zone for me. but i'll do my best to see if its possible to fix it in my code.

**Comment by its-cue** [comment]
Ahh ok, gotcha. Figured I'd take a swing at it and I think I have a solution, 

Toggling the configs and making sure they apply
https://github.com/user-attachments/assets/d3c7f837-c5e7-49b7-8046-dfe40cb67ee5

Checking if the sprite id and offset are applying, as well as clearing when needed
https://github.com/user-attachments/assets/cf468524-d22b-4fbb-9200-e13c6f03f8c1

Poison being cleared (should work for the other versions)
https://github.com/user-attachments/assets/49f3960b-20ea-4022-bed5-16e62d0550ff


![image](https://github.com/user-attachments/assets/17df1b9e-3ec7-46e4-95b0-bf08d29465b4)

You'd need Ron to add these sprites to sample-vanilla and handle them similar to Bank Tags, I don't think it should be a problem. 

I can make a PR sometime tomorrow if you wanna review it

**Comment by Varietyz** [comment]
> Ahh ok, gotcha. Figured I'd take a swing at it and I think I have a solution,
> 
> Toggling the configs and making sure they apply https://github.com/user-attachments/assets/d3c7f837-c5e7-49b7-8046-dfe40cb67ee5
> 
> Checking if the sprite id and offset are applying, as well as clearing when needed https://github.com/user-attachments/assets/cf468524-d22b-4fbb-9200-e13c6f03f8c1
> 
> Poison being cleared (should work for the other versions) https://github.com/user-attachments/assets/49f3960b-20ea-4022-bed5-16e62d0550ff
> 
> ![image](https://private-user-images.githubusercontent.com/126547120/378254875-17df1b9e-3ec7-46e4-95b0-bf08d29465b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTg0MjMsIm5iZiI6MTcyOTQ5ODEyMywicGF0aCI6Ii8xMjY1NDcxMjAvMzc4MjU0ODc1LTE3ZGYxYjllLTNlYzctNDZlNC05NWIwLWJmMDhkMjk0NjViNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwODA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODAwZDBlY2JjYjFmNWRmNGNjNzc2MDIwY2ZjNTNiYzUwODU3YzAxMDQyYmNjYzgwMjg5ODQ3MWYwODdkODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U0AunVrfVDsKWRSu1QN5ZcarN9n5mxmUNJHHT2Xrdg0)
> 
> You'd need Ron to add these sprites to sample-vanilla and handle them similar to Bank Tags, I don't think it should be a problem.
> 
> I can make a PR sometime tomorrow if you wanna review it

Yeah, can do mate! i dont mind contributions :p
i do remember reaching out to ron about these 3 sprites being added to the resource pack plugin
He was going to give it a look, not sure if he has done this by now or not.

It be great to have them in there, would allow some work around for us.

**Comment by Varietyz** [comment]
https://github.com/runelite/plugin-hub/pull/6843

Commit awaiting approval.
Issue Solved
